---
- hosts: webserver
  become: yes
  tasks:
  - name: update packages & install apache2
    apt:
      name: apache2
      update_cache: yes
      state: present
    when: ansible_os_family == "Debian"
  - name: update package & install httpd 
    yum:
      name: httpd
      update_cache: yes
      state: present
    when:  ansible_os_family == "RedHat"
  - name: enable & start service
    service:
      name: apache2
      enabled: yes
      state: started
    when: ansible_os_family == "Debian"
  - name: enable & start service
    service:
      name: httpd
      enabled: yes
      state: started    
    when:  ansible_os_family == "RedHat"  
