---
- hosts: all
  become: yes
  tasks:
  - name: install apache2
    apt:
      name: apache2
      update_cache: yes
      state: present
  - name: start apache2
    service:
      name: apache2
      enabled: yes
      state: started  
---
- hosts: all
  become: yes
  tasks:
  - name: install tree
    apt:
      name: tree
      update_cache: yes
      state: present